version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: intern_db
      MYSQL_ROOT_PASSWORD: Devendra@1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/intern_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Devendra@1234

volumes:
  mysql-data:
